// Copyright (c) 2021 Sendbird, Inc. All rights reserved.

#ifndef SENDBIRD_SBDUSERMESSAGE_H_
#define SENDBIRD_SBDUSERMESSAGE_H_

#include "SBDBaseMessage.h"
#include "SBDBaseChannel.h"

class SBDCommand;
class SBDBaseChannel;
class FSBDUserMessage;

/**
 * The `SBDUserMessage` class represents the user <span>message</span> which is generated by a user via [`SendUserMessage`]() in `SBDBaseChannel`
 * or [Platform API](https://docs.sendbird.com/platform#messages_3_send).
 */
class SBDUserMessage final : public SBDBaseMessage {
public:
	/**
	 * The message sender.
	 */
	SBDUser sender;

	/**
	 * <span>Message</span> text.
	 */
	std::wstring message;

	/**
	 * Data of <span>message</span>.
	 */
	std::wstring data;

	/**
	 * Request ID for checking ACK.
	 */
	std::wstring request_id;

	/**
	 * Custom message type.
	 */
	std::wstring custom_type;

	/**
	 * Translated <span>message</span> text.
	 */
	std::map<std::wstring, std::wstring> translations;

	/**
	 * Returns sender of the <span>message</span>.
	 */
	SBDUser& GetSender();

private:
	SBDUserMessage(const std::string& dict);
	void SetSender(const SBDUser& sender);
	void Overwrite(SBDUserMessage* message);

	friend FSBDUserMessage;
};

#endif /* SENDBIRD_SBDUSERMESSAGE_H_ */
